### ISSUE TITLE
Error when import in dependency

### ISSUE THREAD

**Issue by jeremygiles** [geftimov/android-patternview#13]
Error: Attribute "dotColor" has already been defined

**Comment by geftimov** [comment]
You probably have this attribute in another library or in your project.

**Comment by geftimov** [comment]
@jeremygiles Did you find the problem?

**Comment by jeremygiles** [comment]
Hi @geftimov I had a problem with my connection i thing. I changed wifi spot and it's ok.

**Comment by geftimov** [comment]
Ok , I will close this one.
