### ISSUE TITLE
vibration option

### ISSUE THREAD

**Issue by murat-mehmet** [geftimov/android-patternview#14]
is there any fast way to disable vibration on cell touch?

**Comment by geftimov** [comment]
Not for now.
I can a small change to be able to disable it.
I will try to do it today.

**Comment by murat-mehmet** [comment]
any news about this? at least you can guide me where to modify so i fork project please?

**Comment by geftimov** [comment]
Lol sorry I am working on it, will be released today.

**Comment by geftimov** [comment]
There is such an option if 

``` java
patternView.setTactileFeedbackEnabled(false);
```
