### ISSUE TITLE
Why is the minimum sdk level 14? Can you use 9?

### ISSUE THREAD

**Issue by dmitrikudrenko** [geftimov/android-patternview#3]
I'd like to support old devices (min 9 api level), but I can't.

**Comment by geftimov** [comment]
It is generally better to support API 14 and above.
But in your case i understand that you need API 9.

It is related with the animations.
I will see today what can I do about this issue.
I will keep you posted.

**Comment by dmitrikudrenko** [comment]
I forked patternview-project and changed min sdk level on 9. It built successfully. Can you upload new version with fixed level in maven central?

**Comment by geftimov** [comment]
You need to make pull request of your fork.
And if everything is allright I will merge it and upload it to maven.

**Comment by geftimov** [comment]
from version 1.0.2
