### ISSUE TITLE
I can't use attribute dotColor...

### ISSUE THREAD

**Issue by namooplus** [geftimov/android-patternview#7]
Studio says that there is no attribute : dotColor

But in README, it makes me be able to use this attribute. Is there anything I have to keep in mind?

**Comment by geftimov** [comment]
Sorry , I did not updated the version to maven.

When I upload version 1.0.4 to maven you can use it.

**Comment by geftimov** [comment]
I will do it today.

**Comment by namooplus** [comment]
When will you upload it to maven?
I'm looking forward to it XD
- I have one more question.
  Can I set dotColor, circleColor, and pathColor programmatically in java?

**Comment by namooplus** [comment]
Oh Thx I saw you would upload it today after I finished commenting :P

**Comment by geftimov** [comment]
Done for version [1.0.4](https://github.com/geftimov/android-patternview/releases/tag/1.0.4)
