### ISSUE TITLE
Some suggestions, not a problem.

### ISSUE THREAD

**Issue by namooplus** [geftimov/android-patternview#8]
Using patternview in my project, I have some suggestions for it.
1. Lollipop-like Pattern View
   If I set "circleColor" to transparent, it looks like lollipop a little but not perfectly. Lollipop-like animation and just white&black color may look good.
2. Set color programmatically
   I want to set the color programmatically through setting.
3. When I set color to white or anything, the color seems to have a little bit gradient. Just like...low quality image? (the edge of dot looks like 8-bit image)

**Comment by geftimov** [comment]
Hello , yesterday I was thinking about your suggestions and they seems a good addition/change to the library. 
I have a question though:
Can you provide me a image of how do you think the lollipop style should look like?

**Comment by LafunderTech** [comment]
It's a really good library. If you could add setting color dynamically.

**Comment by geftimov** [comment]
Setting colours dynamically is now possible from version [1.0.6](https://github.com/geftimov/android-patternview/releases/tag/1.0.6).
